### ISSUE TITLE
Suggestion: rename functions like 'Calculate' and 'LoadFile'

### ISSUE THREAD

**Issue by ghost** [gluc/ahp#1]
I can imagine a lot of packages use similar function names; those sound very generic but are there only for a specific package / file format. Maybe 'CalculateAHP', 'LoadFileAHP' would be better? Just an idea.

**Comment by gluc** [comment]
I absolutely get your point, and I realise I have a very strict view on this. But for me, neither the ubiquitous prefixing (e.g. ahp_calculate) nor your postfix suggestion make sense. In my view, R namespaces already solve this adequately. So you can use simply `ahp::Calculate` if you fear interference with other packages. Also, e.g. RStudio lists all the ahp functions if you type ahp:: . And explicitly referencing the namespace keeps your code clean and expressive.  
What do you think? Or have you encountered situations where writing `LoadFileAHP(...)` is strictly preferrable to `ahp::LoadFile(...)`?

**Comment by jjangkr** [comment]
I edited little bit on "car.ahp" file to test and rename it as "car2.ahp".
Then I tried to load it.

The error message for this is as below;

> library(ahp)
> ahpFile2 <- system.file("extdata", "car2.ahp", package="ahp")
> carAhp2 <- LoadFile(ahpFile2)
Warning message:
In file(con, "r") :
  file("") only supports open = "w+" and open = "w+b": using the former


How do I handle it?
Do I have to make "examle.ahp" by using "yaml" type file?
Then how can I edit and save "yaml" file. 
Text editor is not working.

**Comment by ghost** [comment]
Agreed. (The idea just stems from the habit how R coding is done mostly in the wild/in scripts, i.e. calling a function without explicitly stating its package/namespace but doing `library()` first and then calling the function by its simple name.)
