### ISSUE TITLE
loadFile

### ISSUE THREAD

**Issue by tyokota** [gluc/ahp#3]
Attempted to follow this vignette: http://qualityandinnovation.com/2016/01/05/analytic-hierarchy-process-ahp-using-preferencefunction-in-ahp/.

Trying to load a txt file, and I am getting this error:

In readLines(input) : incomplete final line found on 'tomdickharry.txt'

> packageVersion("ahp")
> [1] ‘0.1.1’

**Comment by gluc** [comment]
I think this was a bug in 0.1.1 that should be fixed on dev.
For the time being, as a workaround, you can just add a newline at the end of the file (essentially open in an editor, go to the end, and press Enter). Let me know if that doesn't work.

**Comment by tyokota** [comment]
Thank you, gluc. That workaround works. Looking forward to the next release!
