### ISSUE TITLE
problem in writing ahp

### ISSUE THREAD

**Issue by nirmalngp** [gluc/ahp#9]
@gluc 
I have written an ahp file in YAML 
now when I am running Calculate (ahp) in R, it shows

Warning messages:
1: In is.na(x$consistency) :
  is.na() applied to non-(list or vector) of type 'NULL'
2: In is.na(x$consistency) :
  is.na() applied to non-(list or vector) of type 'NULL'
3: In is.na(x$consistency) :
  is.na() applied to non-(list or vector) of type 'NULL'
4: In is.na(x$consistency) :
  is.na() applied to non-(list or vector) of type 'NULL'
5: In is.na(x$consistency) :
  is.na() applied to non-(list or vector) of type 'NULL'
> 

however, when I run Visualize(ahp), the tree comes well.

pls help me out

**Comment by gluc** [comment]
Without a reproducible example, I'm afraid I won't be able to help, sorry.

**Comment by nirmalngp** [comment]
It's done.
I successfully completed it

On 27 Feb 2017 3:41 p.m., "Christoph Glur" <notifications@github.com> wrote:

Closed #9 <https://github.com/gluc/ahp/issues/9>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gluc/ahp/issues/9#event-978079903>, or mute the thread
